#### <center>Intermediate Python and Software Enginnering</center>


## <center>Section 06 - Numpy - Exercise Solutions</center>


### <center>Innovation Scholars Programme</center>
### <center>King's College London, Medical Research Council and UKRI <center>

### Exercise 1.1:
Import numpy and convert `numbers` to a numpy array by applying np.array or another function to it, be sure the `dtype` of the array is an integer type like `int32`.

In [3]:
import numpy as np
numbers = [411, 131, 272, 737, 129, 591, 943, 801, 62, 357, 199, 814, 136, 523, 556, 55, 860, 943, 411, 760]

arr = np.array(numbers, dtype=np.int32)
print(arr.shape, arr.ndim, arr.dtype)

(20,) 1 int32


### Exercise 1.2:
Calculate the cumulative sum of `arr` starting with an empty array with the same shape/type as `arr`:

In [2]:
# zeros_like creates a new array of the same type/size but with zeros
cumsum = np.zeros_like(arr) 

for i in range(1, cumsum.shape[0] + 1):
    cumsum[i-1] = np.sum(arr[:i])
    
print(cumsum)
print(np.all(cumsum == np.cumsum(arr)))

[ 411  542  814 1551 1680 2271 3214 4015 4077 4434 4633 5447 5583 6106
 6662 6717 7577 8520 8931 9691]
True


### Exercise 1.3:
We can store `n` cartesian coordinates having `D` dimensions in arrays with shape [n,D]. Provide a definition for the routine below to calculate the euclidean length of these vectors for any value of `D`, ei. for 2D vector components `x` and `y` calculate `sqrt(x**2+y**2)`. Keep in mind that functions in Numpy are vectorized operations. Refer to the documentation of `numpy.sum` for a hint of how to do this.

In [3]:
def length(vecs):
    """Calculate a array of shape (n,) containing the lengths of coordinates in `vecs` with shape (n,D)."""
    return np.sqrt(np.sum(vecs ** 2, 1))


vecs = np.asarray([
    (0, 1), # length of 1
    (0, 0), # length of 0
    (3, 4) # length of 5
])

print(vecs.shape, length(vecs))

(3, 2) [1. 0. 5.]


### Exercise 1.4:
Rescale `arr` to the interval [0,1], ie. so that the smallest number becomes 0 and largest 1. Be careful of dtypes of your arrays. 

In [4]:
def rescale(a):
    """Return the rescaled version of a on the [0,1] interval."""
    minv = a.min()
    maxv = a.max()
    return (a - minv) / (maxv - minv)


print(rescale(arr))

[0.4009009  0.08558559 0.24436937 0.76801802 0.08333333 0.6036036
 1.         0.84009009 0.00788288 0.34009009 0.16216216 0.85472973
 0.09121622 0.52702703 0.56418919 0.         0.90653153 1.
 0.4009009  0.79391892]


### Exercise 1.5:
Define a function which flips a randomly chosen axis of an input (see `numpy.random` for suggestions on how to do random choice). The input can be any dimensionality (1D, 2D, 3D, etc.) which you can check with the `ndim` member. A 2D array `a` flipped in the first dimension would be `a[::-1,:]`. You'll probably want to use `slice` objects to represent the indices of the output somehow.

In [30]:
def flip(a):
    """Flip a randomly chosen axis of `a`."""
    slices = [slice(None)] * a.ndim
    ind = np.random.randint(0, a.ndim)
    print(ind)
    slices[ind] = slice(None, None, -1)
    return a[tuple(slices)]

test = np.arange(5)
print(np.all(flip(test) == test[::-1]))  # basic sanity check for a 1D array

print(flip(arr))

0
True
0
[760 411 943 860  55 556 523 136 814 199 357  62 801 943 591 129 737 272
 131 411]


### Exercise 1.6:
Below is a function for finding the first index of the maximal value in a 2D array. It's not particularly efficient and works only for 2D arrays. Consider improving it with some of the better routines for iterating over Numpy arrays, including adding support for arbitrary dimensions and finding all indices of the maximal value (which can be a one-liner with the right routines).

In [55]:
def max_index(a):
    """Return the *first* index of the maximal value in 2D array `a`."""
    
    inds = (0, ) * a.ndim
    max_val = a[inds]
    print(max_val)
    print(inds)

    for i  in np.ndindex(*a.shape):
        if a[i] > max_val:
            inds = (i)
            max_val = a[i]

    return inds


#    return tuple(np.argwhere(a==a.max())[0]) # or just this


test = np.random.randint(0, 100, (20, 20))

print(max_index(test))

73
(0, 0)
(0, 4)


### Exercise 1.7:
We've seen how to select a view of all the values in an array matching some criteria with boolean expressions. Define a function which selects the instances of the maximal value in an array and sets every odd one to 0 only. Eg. an array `[3,4,1,4,-2,2,0,-1,4,4]` would become `[3,0,1,4,-2,2,0,-1,0,4]`. There are other routines for finding places where values are considered True in arrays (eg. `where`).

In [62]:
def zero_odd_maxes(a):
    """Zero out every odd maximal value in `a`."""
    b = a.copy()
    inds = np.argwhere(a == a.max())
    print(inds)
    b[inds[1::2]] = 0
    return b


test = np.random.randint(0, 10, (30,))

print(test)
print(zero_odd_maxes(test))

[0 0 5 1 3 7 4 2 2 8 9 8 9 9 3 7 1 3 8 6 2 3 2 4 1 4 9 7 3 9]
[[10]
 [12]
 [13]
 [26]
 [29]]
[0 0 5 1 3 7 4 2 2 8 9 8 0 9 3 7 1 3 8 6 2 3 2 4 1 4 0 7 3 9]
